<?php
namespace SchemaPress;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * the Tailwind safelist generator.
 *
 * Tailwind's compiler only sees files, so classes typed into the schema editor
 * live somewhere it never looks - the database - and get purged from the built
 * CSS. The class attribute still renders; the rules behind it simply do not
 * exist, which fails silently and looks like a styling bug rather than a build
 * one.
 *
 * Writing every class the schemas use into a plain file gives the compiler
 * something to scan. It regenerates whenever a schema is saved, so the only
 * remaining step is rebuilding the CSS.
 */
class Tailwind
{
    const DIRECTORY = 'generated';
    const FILENAME = 'tailwind-safelist.txt';

    /**
     * regenerates the file whenever a schema definition is stored.
     */
    public function __construct()
    {
        add_action('schemapress/schema_saved', [$this, 'regenerate']);
    }

    /**
     * the absolute path of the generated file.
     *
     * @return string
     */
    public static function path()
    {
        return SCHEMAPRESS_PATH . self::DIRECTORY . '/' . self::FILENAME;
    }

    /**
     * the path a theme's tailwind.config.js should scan, relative to the theme
     * directory - which is where that config file lives.
     *
     * @return string
     */
    public static function relativePath()
    {
        $from = wp_normalize_path(get_stylesheet_directory());
        $to = wp_normalize_path(self::path());

        $fromParts = explode('/', trim($from, '/'));
        $toParts = explode('/', trim($to, '/'));

        while ($fromParts && $toParts && $fromParts[0] === $toParts[0]) {
            array_shift($fromParts);
            array_shift($toParts);
        }

        return './' . str_repeat('../', count($fromParts)) . implode('/', $toParts);
    }

    /**
     * collects every class used across every schema and writes the file.
     *
     * @return string[] the classes written
     */
    public function regenerate()
    {
        $classes = [];

        foreach (SchemaRepository::all() as $schema) {
            $definition = SchemaRepository::definition($schema->ID);

            foreach ($definition['sections'] as $section) {
                self::collect($section['fields'], $classes);
            }
        }

        /**
         * filters the classes written to the safelist.
         *
         * a front-end that maps layout tokens to utility classes can add them
         * here, since those never appear in the schema itself.
         *
         * @param string[] $classes
         */
        $classes = apply_filters('schemapress/safelist', array_values(array_unique($classes)));

        sort($classes);

        self::write($classes);

        return $classes;
    }

    /**
     * walks a field list, gathering class names.
     *
     * @param array $fields
     * @param array $classes by reference
     *
     * @return void
     */
    private static function collect(array $fields, array &$classes)
    {
        foreach ($fields as $field) {
            if (!empty($field['classes'])) {
                foreach (preg_split('/\s+/', $field['classes']) as $class) {
                    if ($class !== '') {
                        $classes[] = $class;
                    }
                }
            }

            if (!empty($field['fields'])) {
                self::collect($field['fields'], $classes);
            }
        }
    }

    /**
     * writes the safelist.
     *
     * one class per line: Tailwind's extractor pulls candidate strings out of
     * any file type, so a plain list needs no wrapper syntax to be understood.
     *
     * @param string[] $classes
     *
     * @return boolean
     */
    private static function write(array $classes)
    {
        $directory = SCHEMAPRESS_PATH . self::DIRECTORY;

        if (!wp_mkdir_p($directory)) {
            return false;
        }

        $header = "/* Generated by SchemaPress. Do not edit.\n"
            . "   Add this file to the `content` array in your tailwind.config.js\n"
            . "   so classes stored in schemas survive the CSS build. */\n";

        return (bool) file_put_contents(
            self::path(),
            $header . implode("\n", $classes) . "\n"
        );
    }
}
